{% set name = "starz" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/starz-{{ version }}.tar.gz
  sha256: a564eba0e5f487e26c6be0c07ebb6bba204f5a4e4815af0d9fd49113152a537a

build:
  number: 0
  noarch: python
  entry_points:
    - starz=starz.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - filetype
    - python >=3.7
    - tqdm

test:
  imports:
    - starz
  commands:
    - pip check
    - starz --help
  requires:
    - pip

about:
  home: https://github.com/Semi-ATE/starz
  summary: Sized Tape ARchiveZ
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nerohmot
