{% set name = "starz" %}
{% set version = "0.2.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/starz-{{ version }}.tar.gz
  sha256: 4ee4e8f37ada9edad55353c5c1396361b2623f6213cf80fe18bdf2373a6282d5

build:
  number: 0
  noarch: python
  entry_points:
    - starz=starz.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - filetype
    - python >=3.7
    - tqdm

test:
  imports:
    - starz
  commands:
    - pip check
    - starz --help
  requires:
    - pip

about:
  home: https://github.com/Semi-ATE/starz
  summary: Sized Tape ARchiveZ
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nerohmot
