{% set name = "starz" %}
{% set version = "0.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/starz-{{ version }}.tar.gz
  sha256: 37ce59b7892a95ed0209d28c3e133b50d9cfab047d0ba0b5bfd625969b5d1350

build:
  number: 0
  noarch: python
  entry_points:
    - starz=starz.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - filetype
    - python >=3.7
    - tqdm

test:
  imports:
    - starz
  commands:
    - pip check
    - starz --help
  requires:
    - pip

about:
  home: https://github.com/Semi-ATE/starz
  summary: Sized Tape ARchiveZ
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nerohmot
